# Enable/Disable Built-In Features
aha_board: false
question_board: false


# Custom Sidebar Links to External Sites.
# ----------------------------------------
# Must be an array.  Start with a dash on its own line.
# Then indent and provide label, url, and fa icon (optional)
# The default icon is fa-cloud.
sidebar:

  -
    label: Syllabus
    url: 'https://github.com/GoLearnToCode/kiei925-winter17/raw/master/files/KIEI-925-0-80_Winter2017.pdf'
    icon: fa-list-ol
  -
    label: Canvas
    url: "https://canvas.northwestern.edu/courses/47675"
    icon: fa-comments
  -
 
